import type { FC } from "react";
import type { TComponentTypes } from "@codigo/schema";
import {
  ButtonComponent,
  CardComponent,
  ImageComponent,
  ListComponent,
  StatisticComponent,
  SwiperComponent,
  TableComponent,
  VideoComponent,
  TextComponent,
  SplitComponent,
  EmptyComponent,
  RichTextComponent,
  QrcodeComponent,
  AlertComponent,
  InputComponent,
  TextAreaComponent,
  RadioComponent,
  CheckboxComponent,
  BarChartComponent,
  LineChartComponent,
  PieChartComponent,
} from "..";

// @ts-ignore
export const componentList: Record<TComponentTypes, FC<any>> = {
  button: ButtonComponent,
  video: VideoComponent,
  image: ImageComponent,
  swiper: SwiperComponent,
  card: CardComponent,
  list: ListComponent,
  statistic: StatisticComponent,
  table: TableComponent,
  titleText: TextComponent,
  split: SplitComponent,
  empty: EmptyComponent,
  richText: RichTextComponent,
  qrcode: QrcodeComponent,
  alert: AlertComponent,
  input: InputComponent,
  textArea: TextAreaComponent,
  radio: RadioComponent,
  checkbox: CheckboxComponent,
  barChart: BarChartComponent,
  lineChart: LineChartComponent,
  pieChart: PieChartComponent,
};
